
using CommunityToolkit.Mvvm.DependencyInjection;
using POS_APP.ViewModels.LoginViewModels;
using System.Windows;
using System.Windows.Controls;


namespace POS_APP.Views.LoginViews
{
    /// <summary>  
    /// Interaction logic for BranchLoginView.xaml  
    /// </summary>  
    public partial class BranchLoginView : UserControl
    {
        public BranchLoginView()
        {
            InitializeComponent(); // Ensure this method is generated by the XAML compiler
        }
        private void PasswordBox_PasswordChanged(object sender, RoutedEventArgs e)
        {
            if (DataContext is BranchLoginViewModel viewModel)
            {
                viewModel.Password = PasswordBox.Password;
            }
        }
    }
}
